// react-components/src/components/pagination/Pager.js
import React, { useState, useEffect } from 'react';
import { generatePages } from '../../util';

function Pager(props) {
  const { totalPage, defaultCurrent, onChange } = props;
  const [current, setPage] = useState(defaultCurrent);
  const pages = Object.entries(generatePages(totalPage));

  let centerPages = [];

  const centerSize = 5; // 中间的页数，默认为5

  // 以下字段均基于 centerSize 计算而来
  const sideSize = (centerSize - 1) / 2;
  const jumpSize = centerSize;
  const startEllipsisSize = centerSize + 3;
  const maxLeftSize = centerSize + 1;

  const updateCenterPage = () => {
    let centerPage = current;
    if (current > pages.length - 3) {
      centerPage = pages.length - 3;
    }
    if (current < 4) {
      centerPage = 4;
    }
    if (pages.length <= startEllipsisSize) {
      const centerPage = [];
      for (let i = 2, len = pages.length; i < len; i++) {
        centerPage.push(i);
      }
      centerPages = centerPage;
    } else {
      centerPages = [centerPage - 2, centerPage - 1, centerPage, centerPage + 1, centerPage + 2 ];
    }
  }

  updateCenterPage();

  useEffect(() => {
    setPage(defaultCurrent);
  });

  return (
    <ul className="m-pager">
      <li className={'number' + (current == 1 ? ' active' : '')}
        onClick={() => {
          setPage(1);
          onChange(1);
        }}
      >1</li>

      {
        current >= centerSize && pages.length >= startEllipsisSize
        && <li className="more left" 
          onClick={() => {
            let newPage = current - jumpSize;
            if (newPage < 1) {
              newPage = 1;
            }
            setPage(newPage);
            onChange(newPage);
          }}
        ></li>
      }

      {
        centerPages.map((page, key) => {
          return (
            <li key={key} className={'number' + (page == current ? ' active' : '')}
              onClick={() => {
                setPage(page);
                onChange(page);
              }}
            >{ page }</li>
          );
        })
      }
      
      {
        current <= pages.length - centerSize + 1 && pages.length >= startEllipsisSize
        && <li className="more right" 
          onClick={() => {
            let newPage = current + jumpSize;
            if (newPage > pages.length) {
              newPage = pages.length;
            }
            setPage(newPage);
            onChange(newPage);
          }}
        ></li>
      }

      { 
        pages.length !== 1 
        && <li className={'number' + (pages.length == current ? ' active' : '')}
            onClick={() => {
              setPage(pages.length);
              onChange(pages.length);
            }}
          >{ pages.length }</li>
      }
    </ul>
  );
}

export default Pager;

// vue-components/src/components/pagination/Pager.vue
<script>
import Vue from 'vue';
import { generatePages } from '@/util';

export default {
  name: 'Pager',
  components: {
  },
  props: {
    totalPage: {
      type: Number,
      // default: 2
    },
    defaultCurrent: {
      type: Number,
    }
  },
  data() {
    return {
      pages: generatePages(this.totalPage),
      current: this.defaultCurrent,
    }
  },
  computed: {
    pageList: function() {
      return Object.entries(this.pages)
    },
  },
  watch: {
    defaultCurrent: {
      handler(newValue, oldValue) {
        this.current = newValue;
      }
    }
  },
  methods: {
    setPage(pageKey) {
      for (let page in this.pages) {
        this.pages[page].active = false;
      }
      this.pages[pageKey].active = true;
    },
    getCurrent() {
      const activePage = Object.entries(this.pages).filter(pageItem => pageItem[1].active);
      if (activePage && activePage.length !== 0) {
        return +activePage[0][0];
      }
      return 0;
    },
    clickPage(pageKey) {
      this.setPage(pageKey);
      this.current = pageKey;
      this.$emit('change', this.getCurrent());
    }
  },
  render(createElement) {
      const centerSize = 5; // 中间的页数，默认为5

      // 以下字段均基于 centerSize 计算而来
      const sideSize = (centerSize - 1) / 2;
      const jumpSize = centerSize;
      const startEllipsisSize = centerSize + 3;
      const maxLeftSize = centerSize + 1;

      const pages = [];
      let noLeftMore = true;
      let noRightMore = true;
      for (let pageIndex = 0, pageLen = this.pageList.length; pageIndex < pageLen; pageIndex++) {
        const pageItem = this.pageList[pageIndex];
        const [ pageKey, page ] = pageItem;

        const normalPage = createElement('li', {
          class: {
            number: true,
            active: pageKey == this.current
          },
          on: {
            click: () => { 
              this.clickPage(pageKey); 
            }
          }
        }, page.label);

        const leftMorePage = createElement('li', {
          class: {
            more: true,
            left: true
          },
          on: {
            click: () => { 
              let newPage = this.current - jumpSize;
              if (newPage < 1) {
                newPage = 1;
              }
              this.clickPage(newPage); 
            }
          }
        });

        const rightMorePage = createElement('li', {
          class: {
            more: true,
            right: true
          },
          on: {
            click: () => { 
              let newPage = this.current + jumpSize;
              if (newPage > this.pageList.length) {
                newPage = this.pageList.length;
              }
              this.clickPage(newPage);
            }
          }
        });

        if (this.pageList.length < startEllipsisSize) {
          // console.log(`总页数 < ${startEllipsisSize}`);
          pages.push(normalPage);
        } else {
          // console.log(`总页数 >= ${startEllipsisSize}`);
          if (this.current < centerSize) {
            // console.log(`当前页码 < ${centerSize}`);
            if (pageIndex === this.pageList.length - 1 || pageIndex < maxLeftSize) {
              pages.push(normalPage);
            } else {
              noRightMore && pages.push(rightMorePage);
              noRightMore = false;
            }
          } else if (this.current > this.pageList.length - centerSize + 1) {
            // console.log(`当前页码 > ${this.pageList.length - centerSize + 1}`);
            if (pageIndex === 0 || pageIndex > this.pageList.length - 1 - maxLeftSize) {
              pages.push(normalPage);
            } else {
              noLeftMore && pages.push(leftMorePage);
              noLeftMore = false;
            }
          } else {
            // console.log(`${pageIndex + 1 - sideSize} <= 当前页码 <= ${pageIndex + 1 + sideSize}`);
            // console.log(`或者 当前页码 = 1（首页）`);
            // console.log(`或者 当前页码 = ${pageList.length}（尾页）`);
            if (pageIndex === 0 || pageIndex === this.pageList.length - 1) {
              pages.push(normalPage);
            } else if (pageIndex > 0 && pageIndex < this.current - sideSize - 1) {
              noLeftMore && pages.push(leftMorePage);
              noLeftMore = false;
            } else if (pageIndex >= this.current - sideSize - 1 && pageIndex <= this.current + sideSize - 1) {
              pages.push(normalPage);
            } else if (pageIndex > this.current + sideSize - 1 && pageIndex < this.pageList.length - 1) {
              noRightMore && pages.push(rightMorePage);
              noRightMore = false;
            } else {
              pages.push(normalPage);
            }
          }
        }
      }
      return createElement('ul', {
        class: {
          'm-pager': true
        }
      }, pages);
  }
};
</script>

<style scoped lang="scss">
@import '@/assets/common.scss';

.m-pager {
  list-style: none;
  padding: 0;
  li {
    @include page-button;

    &.active {
      background-color: $blue;
      color: #fff;
      cursor: default;
    }

    &:not(.active):hover {
      color: $blue;
    }

    &.more {
      &::before {
        content: '...';
      }
      &.left:hover::before {
        content: '<<';
      }
      &.right:hover::before {
        content: '>>';
      }
    }
  }
}
</style>
