// react-components/src/components/pagination/Pagination.js
import React, { useState } from 'react';
import Button from './Button';
import Pager from './Pager';

function Pagination(props) {
  const { total, defaultCurrent, defaultPageSize, onChange } = props;
  const [current, setPage] = useState(defaultCurrent);
  const totalPage = Math.ceil(total / defaultPageSize);
  return (
    <div className="m-pagination">
      <Button className="btn-prev" onClick={() => {
        if (current < 2) return;
        setPage(current - 1);
        onChange(current - 1);
      }}>&lt;</Button>
      <Pager totalPage={totalPage} defaultCurrent={current} onChange={(current) => {
        setPage(current);
        onChange(current);
      }}></Pager>
      <Button className="btn-next" onClick={() => {
        if (current >= totalPage) return;
        setPage(current + 1);
        onChange(current + 1);
      }}>></Button>
    </div>
  );
}

export default Pagination;

// ng-components/src/app/components/pagination/pagination.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";

@Component({
  selector: 'd-pagination',
  template: `
    <div>
      <d-button class="btn-prev" (btnClick)="prevPage()">&lt;</d-button>
      <d-pager [totalPage]="totalPage" [defaultCurrent]="defaultCurrent" (onChange)="onPageChange"></d-pager>
      <d-button class="btn-next" (btnClick)="nextPage()">></d-button>
    </div>
  `,
})
export class PaginationComponent {
  @Input() total: number;
  @Input() defaultCurrent = 1;
  @Input() defaultPageSize: number;
  @Output() onChange = new EventEmitter();

  @Input()
  get totalPage() {
    return Math.ceil(this.total / this.defaultPageSize);
  }

  current = 1;

  prevPage() {
    if (this.current < 2) return;
    this.current--;
    this.onChange.emit(this.current);
  }

  nextPage() {
    if (this.current > this.totalPage - 1) return;
    this.current++;
    this.onChange.emit(this.current);
  }

  onPageChange() {

  }
}

<div class="m-pagination">
  <d-button 
    class="btn-prev" 
    (btnClick)="setPage(current - 1)"
  >&lt;</d-button>
  <d-pager 
    [totalPage]="totalPage" 
    [defaultCurrent]="current" 
    (onChange)="onPageChange($event)"
  ></d-pager>
  <d-button 
    class="btn-next" 
    (btnClick)="setPage(current + 1)"
  >></d-button>
</div>
