// ng-components/src/app/components/pagination/pager.component.ts
import { Component, Input, Output, EventEmitter, OnInit, SimpleChanges } from "@angular/core";
import { generatePages } from 'src/app/util';

@Component({
  selector: 'd-pager',
  templateUrl: './pager.component.html',
  styleUrls: ['./pager.component.scss']
})
export class PagerComponent implements OnInit {
  @Input() totalPage: number;
  @Input() defaultCurrent = 1;
  @Output() onChange = new EventEmitter();

  pages;
  current = this.defaultCurrent;

  centerPages = [];

  centerSize = 5; // 中间的页数，默认为5

  // 以下字段均基于 centerSize 计算而来
  sideSize = (this.centerSize - 1) / 2;
  jumpSize = this.centerSize;
  startEllipsisSize = this.centerSize + 3;
  maxLeftSize = this.centerSize + 1;

  ngOnInit() {
    this.pages = Object.entries(generatePages(this.totalPage));
    this.updateCenterPage();
  }

  updateCenterPage() {
    let centerPage = this.current;
    if (this.current > this.pages.length - 3) {
      centerPage = this.pages.length - 3;
    }
    if (this.current < 4) {
      centerPage = 4;
    }
    if (this.pages.length <= this.startEllipsisSize) {
      const centerPage = [];
      for (let i = 2, len = this.pages.length; i < len; i++) {
        centerPage.push(i);
      }
      this.centerPages = centerPage;
    } else {
      this.centerPages = [centerPage - 2, centerPage - 1, centerPage, centerPage + 1, centerPage + 2 ];
    }
  }

  clickPage($event, page) {
    this.current = page;
    this.updateCenterPage();
    this.onChange.emit(this.current);
  }

  leftMorePage() {
    let newPage = this.current - this.jumpSize;
    if (newPage < 1) {
      newPage = 1;
    }
    this.current = newPage;
    this.updateCenterPage();
    this.onChange.emit(this.current);
  }

  rightMorePage() {
    let newPage = this.current + this.jumpSize;
    if (newPage > this.pages.length) {
      newPage = this.pages.length;
    }
    this.current = newPage;
    this.updateCenterPage();
    this.onChange.emit(this.current);
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes.defaultCurrent && changes.defaultCurrent.currentValue) {
      this.current = changes.defaultCurrent.currentValue;

      this.pages = Object.entries(generatePages(this.totalPage));
      this.updateCenterPage();
    }
  }
}
<ul class="m-pager">
  <li [ngClass]="{
      number: true,
      active: 1 == current
    }" 
    (click)="clickPage($event, 1)"
  >1</li>
  <li *ngIf="current >= centerSize && pages.length >= startEllipsisSize" class="more left" 
    (click)="leftMorePage($event)"
  ></li>
  <li *ngFor="let page of centerPages" [ngClass]="{
      number: true,
      active: page == current
    }" 
    (click)="clickPage($event, page)"
  >{{ page }}</li>
  <li *ngIf="current <= pages.length - centerSize + 1 && pages.length >= startEllipsisSize" class="more right" 
    (click)="rightMorePage($event)"
  ></li>
  <li *ngIf="pages.length !== 1" [ngClass]="{
      number: true,
      active: pages.length == current
    }" 
    (click)="clickPage($event, pages.length)"
  >{{ pages.length }}</li>
</ul>

// react-components/src/components/pagination/Pager.js
import React, { useState, useEffect } from 'react';
import { generatePages } from '../../util';

function Pager(props) {
  const { totalPage, defaultCurrent, onChange } = props;
  const [current, setPage] = useState(defaultCurrent);
  const pages = Object.entries(generatePages(totalPage));

  let centerPages = [];

  const centerSize = 5; // 中间的页数，默认为5

  // 以下字段均基于 centerSize 计算而来
  const sideSize = (centerSize - 1) / 2;
  const jumpSize = centerSize;
  const startEllipsisSize = centerSize + 3;
  const maxLeftSize = centerSize + 1;

  const updateCenterPage = () => {
    let centerPage = current;
    if (current > pages.length - 3) {
      centerPage = pages.length - 3;
    }
    if (current < 4) {
      centerPage = 4;
    }
    if (pages.length <= startEllipsisSize) {
      const centerPage = [];
      for (let i = 2, len = pages.length; i < len; i++) {
        centerPage.push(i);
      }
      centerPages = centerPage;
    } else {
      centerPages = [centerPage - 2, centerPage - 1, centerPage, centerPage + 1, centerPage + 2 ];
    }
  }

  updateCenterPage();

  useEffect(() => {
    setPage(defaultCurrent);
  });

  return (
    <ul className="m-pager">
      <li className={'number' + (current == 1 ? ' active' : '')}
        onClick={() => {
          setPage(1);
          onChange(1);
        }}
      >1</li>

      {
        current >= centerSize && pages.length >= startEllipsisSize
        && <li className="more left" 
          onClick={() => {
            let newPage = current - jumpSize;
            if (newPage < 1) {
              newPage = 1;
            }
            setPage(newPage);
            onChange(newPage);
          }}
        ></li>
      }

      {
        centerPages.map((page, key) => {
          return (
            <li key={key} className={'number' + (page == current ? ' active' : '')}
              onClick={() => {
                setPage(page);
                onChange(page);
              }}
            >{ page }</li>
          );
        })
      }
      
      {
        current <= pages.length - centerSize + 1 && pages.length >= startEllipsisSize
        && <li className="more right" 
          onClick={() => {
            let newPage = current + jumpSize;
            if (newPage > pages.length) {
              newPage = pages.length;
            }
            setPage(newPage);
            onChange(newPage);
          }}
        ></li>
      }

      { 
        pages.length !== 1 
        && <li className={'number' + (pages.length == current ? ' active' : '')}
            onClick={() => {
              setPage(pages.length);
              onChange(pages.length);
            }}
          >{ pages.length }</li>
      }
    </ul>
  );
}

export default Pager;
