// vue-components/src/components/pagination/Pagination.vue
<template>
  <div class="m-pagination">
    <Button class="btn-prev" @click="setPage(current - 1)">&lt;</Button>
    <Pager v-bind:total-page="totalPage" v-bind:default-current="current" v-on:change="onChange"></Pager>
    <Button class="btn-next" @click="setPage(current + 1)">></Button>
  </div>
</template>

<script>
// @ is an alias to /src
import Button from './Button.vue';
import Pager from './Pager.vue';

export default {
  name: 'Pagination',
  components: {
    Button,
    Pager,
  },
  // 接口定义 props
  props: {
    defaultCurrent: {
      type: Number,
      // default: 2
    },
    defaultPageSize: {
      type: Number,
      // default: 3
    },
    total: {
      type: Number,
      // default: 24
    },
  },
  data() {
    return {
      current: this.defaultCurrent,
    }
  },
  computed: {
    totalPage: function () {
      return Math.ceil(this.total / this.defaultPageSize);
    },
  },
  methods: {
    setPage(page) {
      if (page < 1) return;
      if (page > this.totalPage) return;
      this.current = page;
      this.$emit('change', this.current);
    },
    onChange(current) {
      this.current = current;
      this.$emit('change', this.current);
    }
  }
};
</script>

<style scoped lang="scss">
@import '@/assets/common.scss';

.m-pagination {
  display: flex;
  align-items: center;
  .btn-prev, .btn-next {
    @include page-button;
    border: none;
  }
}
</style>

// react-components/src/components/pagination/Pagination.js
import React, { useState } from 'react';
import Button from './Button';
import Pager from './Pager';

function Pagination(props) {
  const { total, defaultCurrent, defaultPageSize, onChange } = props;
  const [current, setPage] = useState(defaultCurrent);
  const totalPage = Math.ceil(total / defaultPageSize);
  return (
    <div className="m-pagination">
      <Button className="btn-prev" onClick={() => {
        if (current < 2) return;
        setPage(current - 1);
        onChange(current - 1);
      }}>&lt;</Button>
      <Pager totalPage={totalPage} defaultCurrent={current} onChange={(current) => {
        setPage(current);
        onChange(current);
      }}></Pager>
      <Button className="btn-next" onClick={() => {
        if (current >= totalPage) return;
        setPage(current + 1);
        onChange(current + 1);
      }}>></Button>
    </div>
  );
}

export default Pagination;
